"""Generate frame vectors from Python's `websockets` reference implementation.

Our Lua codec must decode exactly what a real server sends, and must produce
exactly what a real server expects. Rather than open a socket from LuaJIT, which
has no socket library here, both directions are cross-checked against a mature
implementation. Run from the repository root:

    python tools/gen_vectors.py > tests/fixtures/vectors.lua
"""

import sys

from websockets.frames import Frame, Opcode


def lua_string(data: bytes) -> str:
    """Every byte as a decimal escape: safe regardless of Lua's string rules."""
    return '"' + "".join(f"\\{b:d}" for b in data) + '"'


def serialise(frame: Frame, mask: bool, key: bytes | None = None) -> bytes:
    if mask:
        # websockets generates its own key; force ours so Lua can reproduce it.
        raw = frame.serialize(mask=True)
        header_len = len(raw) - len(frame.data) - 4
        body = bytes(b ^ key[i % 4] for i, b in enumerate(frame.data))
        return raw[:header_len] + key + body
    return frame.serialize(mask=False)


INBOUND = [
    ("short text", Frame(Opcode.TEXT, b"mso {}")),
    ("125 byte text", Frame(Opcode.TEXT, b"x" * 125)),
    ("126 byte text", Frame(Opcode.TEXT, b"x" * 126)),
    ("16 bit length", Frame(Opcode.TEXT, b"y" * 4000)),
    ("64 bit length", Frame(Opcode.TEXT, b"z" * 70000)),
    ("mso sized", Frame(Opcode.TEXT, b"m" * 38461)),
    ("empty ping", Frame(Opcode.PING, b"")),
    ("ping payload", Frame(Opcode.PING, b"keepalive")),
    ("empty pong", Frame(Opcode.PONG, b"")),
    ("close", Frame(Opcode.CLOSE, b"")),
]

OUTBOUND_KEY = bytes([0x37, 0xFA, 0x21, 0x3D])
OUTBOUND = [
    ("getmso", Frame(Opcode.TEXT, b"getmso")),
    ("changemso", Frame(Opcode.TEXT, b'changemso [{"op":"replace","path":"/volume","value":-30}]')),
    ("long text", Frame(Opcode.TEXT, b"q" * 300)),
    ("very long text", Frame(Opcode.TEXT, b"q" * 70000)),
    ("ping", Frame(Opcode.PING, b"")),
    ("pong echo", Frame(Opcode.PONG, b"keepalive")),
]


def main() -> None:
    out = sys.stdout
    out.write("-- GENERATED by tools/gen_vectors.py. Do not edit.\n")
    out.write("-- Frames serialised by Python's `websockets`, used to cross-check\n")
    out.write("-- htp1/frame.lua in both directions.\n\n")
    out.write("return {\n  inbound = {\n")
    for name, frame in INBOUND:
        raw = serialise(frame, mask=False)
        out.write(
            f"    {{ name = {lua_string(name.encode())}, "
            f"raw = {lua_string(raw)}, opcode = {int(frame.opcode)}, "
            f"payload = {lua_string(frame.data)} }},\n"
        )
    out.write("  },\n  outbound = {\n")
    out.write(f"    key = {lua_string(OUTBOUND_KEY)},\n")
    for name, frame in OUTBOUND:
        raw = serialise(frame, mask=True, key=OUTBOUND_KEY)
        out.write(
            f"    {{ name = {lua_string(name.encode())}, "
            f"opcode = {int(frame.opcode)}, payload = {lua_string(frame.data)}, "
            f"raw = {lua_string(raw)} }},\n"
        )
    out.write("  },\n}\n")


if __name__ == "__main__":
    main()
